modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "bluemapfrontiers"
version = "${version}"
displayName = "Bluemap Frontiers"
authors = "ErdbeerbaerLP"
description = '''
MapFrontiers integration for Bluemap
'''
#logoFile = ""

[[dependencies.bluemapfrontiers]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.bluemapfrontiers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4]"
ordering = "NONE"
side = "SERVER"

[[dependencies.bluemapfrontiers]]
modId = "bluemap"
mandatory = true
versionRange = "[5,)"
ordering = "NONE"
side = "SERVER"
[[dependencies.bluemapfrontiers]]
modId = "mapfrontiers"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "SERVER"

[[mixins]]
config = "bluemapfrontiers.mixins.json"
