modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "bluemapfrontiers"
version = "${version}"
displayName = "Bluemap Frontiers"
authors = "ErdbeerbaerLP"
description = '''
MapFrontiers integration for Bluemap
'''
#logoFile = ""

[[dependencies.bluemapfrontiers]]
modId = "neoforge"
type = "required"
versionRange = "[20.6,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.bluemapfrontiers]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.bluemapfrontiers]]
modId = "bluemap"
type = "required"
versionRange = "[5,)"
ordering = "NONE"
side = "SERVER"
[[dependencies.bluemapfrontiers]]
modId = "mapfrontiers"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "SERVER"

[[mixins]]
config = "bluemapfrontiers.mixins.json"
